### ISSUE TITLE
fetch Contributors details from github API

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#105] opened 2023-01-25 17:56 UTC
In that case, we have to fetch it two times.
1. Fetch contributors and get users URL
2. then again Fetch this URL to get user information.

We need 
Username,
Profile Picture,
Twitter,
GitHub,
Contributions [from contributors API],

Contributors API
https://api.github.com/repos/devvsakib/github-error-solve/contributors

users API
you will get this URL from the Contributors API
![image](https://user-images.githubusercontent.com/88339569/214644205-b4666b97-06fc-4d22-9547-ab9f8d724f0f.png)

**Comment by AniketNS** [comment] 2023-01-26 05:16
Hey @devvsakib, can you tell me how can I get started to solve this issue?

**Comment by MohamedAlDeep** [comment] 2023-01-26 10:16
@AniketNS Hello man so first of all do you know `fetch()` function

**Comment by MohamedAlDeep** [comment] 2023-01-26 10:22
@AniketNS Oh do you mean in github?

**Comment by AniketNS** [comment] 2023-01-27 04:48
@MohamedAlDeep  No not on GitHub. I've only fetched data from API in Postman. I don't know how to do that with GitHub API.

**Comment by AryanGodara** [comment] 2023-01-30 06:17
Hello @devvsakib, can you please elaborate on this error?
I can work on this, as I have experience with using the github API, but I don't quite understand the issue, from the description, as in what I have to do in a PR.

**Comment by devvsakib** [comment] 2023-01-30 06:45
Actually, we need contributors' Twitter usernames. For this, we have to fetch individual user API. To get the individual user API link, first we have to fetch contributors API.
Contributors API :  https://api.github.com/repos/devvsakib/github-error-solve/contributors

We will get the user API url from this. Then we will fetch user API again to get their details.

for example:
```
fetching contributors->
fetch(contUrl)
 .then(r=> r.json())
 .then(d=>d.url) // user API
```
now we will fetch user API
```
fetch(user)
 .then(r=> r.json())
 .then(d=> their details) // user details
 
```

@AryanGodara

**Comment by AryanGodara** [comment] 2023-01-31 07:20
> Actually, we need contributors' Twitter usernames. For this, we have to fetch individual user API. To get the individual user API link, first we have to fetch contributors API. Contributors API : https://api.github.com/repos/devvsakib/github-error-solve/contributors
> 
> We will get the user API url from this. Then we will fetch user API again to get their details.
> 
> for example:
> 
> ```
> fetching contributors->
> fetch(contUrl)
>  .then(r=> r.json())
>  .then(d=>d.url) // user API
> ```
> 
> now we will fetch user API
> 
> ```
> fetch(user)
>  .then(r=> r.json())
>  .then(d=> their details) // user details
>  
> ```
> 
> @AryanGodara

Thanks @devvsakib , I'll try to work on this issue during the weekend. Again sorry for delay, but I have hectic class schedule right now!

**Comment by iONBain** [comment] 2023-02-25 03:17
Hi @devvsakib if the issue is still open, can I work on it?

**Comment by devvsakib** [comment] 2023-02-25 05:35
> Hi @devvsakib I have worked upon APIs and this issue seems like having nested fetch calls. If the issue is still open, can I work on it ?

sure

**Comment by iONBain** [comment] 2023-02-25 11:48
just to be sure, we need to add the code in documentation page, right? 
path: src > Contributors > contributors.jsx

**Comment by devvsakib** [comment] 2023-02-25 12:48
yes @iONBain

**Comment by iONBain** [comment] 2023-02-26 08:15
Hi @devvsakib ! Created a PR #115. Have a look if everything looks good!

**Comment by iONBain** [comment] 2023-03-07 03:07
i think we can close this issue

**Closed** 2023-03-07 04:55 UTC
Labels: documentation, enhancement, EddieHub:good-first-issue
